# Utiliser l'image officielle de Python comme base
FROM python:3.9.16

# Mettre à jour et installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    git

# Créer un répertoire de travail et définir ce répertoire comme répertoire actif
RUN mkdir /app
WORKDIR /app

# Copier les fichiers de requirements.txt dans le répertoire de travail
COPY requirements.txt /app

# Installer les bibliothèques spécifiées dans requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Installer PyTorch et PyTorch Geometric avec leurs dépendances
RUN pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html
RUN pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://pytorch-geometric.com/whl/torch-1.11.0+cu111.html

# Installer Jupyter Notebook
RUN pip install notebook