name: pytorchenv
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - plotly
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch
  - pip
  - pip:
    - torch-geometric
    - nbformat
    - openai
