wandb_version: 1

batch_size:
  desc: null
  value: 128
devices:
  desc: null
  value: 1
encoder_hidden_size:
  desc: null
  value: 64
encoder_input_size:
  desc: null
  value: -1
encoder_layer_name:
  desc: null
  value: GATConv
encoder_output_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.01
num_workers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
program:
  desc: null
  value: train
method:
  desc: null
  value: grid
name:
  desc: null
  value: autoencoderMnistSuperpixels
description:
  desc: null
  value: Train an autoencoder on MNISTSuperpixels
dataset:
  desc: null
  value: MNISTSuperpixels
data_path:
  desc: null
  value: data/MNISTSuperpixels
model_path:
  desc: null
  value: models/autoencoder
metric:
  desc: null
  value:
    name: train_loss
    goal: minimize
parameters:
  desc: null
  value:
    lr:
      values:
      - 0.01
    optimizer:
      values:
      - adam
    epochs:
      values:
      - 100
    batch_size:
      values:
      - 128
    devices:
      values:
      - 1
    num_workers:
      values:
      - 1
    encoder_layer_name:
      values:
      - GATConv
    encoder_input_size:
      values:
      - -1
    encoder_hidden_size:
      values:
      - 64
      - 128
    encoder_output_size:
      values:
      - 16
      - 32
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.5
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688969216.006183
    t:
      1:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 9
      - 41
      - 49
      - 55
      - 77
      3:
      - 2
      - 5
      - 7
      - 16
      - 23
      4: 3.9.16
      5: 0.15.5
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
