program: generate
method: grid
name: autoencoderMNIST
description: Generation test for autoencoder on MNIST
dataset: MNISTSuperpixels
data_path: data/MNISTSuperpixels/
checkpoint_folder_path: autoencoder
generateNumber: 60
model_paths: ["models/autoencoder/divine-sweep-1.pt"]
probability_of_edge: 0.4
save_emb: data/embeddingMNIST/img/
plot : False
