program: generate
method: grid
name: autoencoderMnistSuperpixelsGeneration
description: Generation test for autoencoder on MNISTSuperpixels
dataset: MNISTSuperpixels
data_path: data/MNISTSuperpixels
checkpoint_folder_path: autoencoder
generateNumber: 10
model_paths: ["models/autoencoder/hopeful-sweep-258.pt"]
probability_of_edge: 0.5