program: generate
method: grid
name: autoencoderMnistSuperpixelsGeneration
description: Generation test for autoencoder on MNISTSuperpixels
dataset: MNISTSuperpixels
data_path: data/MNISTSuperpixels
checkpoint_folder_path: autoencoder
generateNumber: 30
model_paths: ["models/autoencoder/divine-sweep-1.pt"]
probability_of_edge: 0.65