program: train
method: grid
name: autoencoderMnistSuperpixels
description: Train an autoencoder on MNISTSuperpixels
dataset: MNISTSuperpixels
data_path: data/MNISTSuperpixels
model_path: models/autoencoder
metric:
  name: train_loss
  goal: minimize

parameters:
  lr:
    values: [0.1, 0.01, 0.001]
  optimizer:
    values: ["adam", "sgd"]
  epochs:
    values: [10]
  batch_size:
    values: [32, 64, 128]
  devices:
    values: [1]
  num_workers:
    values: [1]
  encoder_layer_name:
    values: ["GATConv", "GCNConv"]
  encoder_input_size: 
    values : [-1]
  encoder_hidden_size:
    values: [64, 128]
  encoder_output_size: 
    values: [4, 8, 16, 32, 64]