wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688962111.101724
    t:
      1:
      - 1
      - 49
      - 55
      - 77
      2:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 77
      3:
      - 23
      4: 3.9.16
      5: 0.15.5
      8:
      - 5
